'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const contract = require('../tools/report/scripts/report_contract');

test('adjacent and sparse citation tokens remain distinct', () => {
  assert.deepEqual(contract.inlineTokens('Memory[^1][^7].'), [
    { text: 'Memory' }, { refId: 1 }, { refId: 7 }, { text: '.' },
  ]);
});
test('nested emphasis preserves the cited text and ID', () => {
  assert.deepEqual(contract.inlineTokens('**Person P001[^7]**'), [
    { text: 'Person P001', bold: true }, { refId: 7 },
  ]);
});
test('plain caption text contains citation numbers without markup', () => {
  assert.equal(contract.plainLabel('*Synthetic caption* [^7]'), 'Synthetic caption 7');
});
test('non-string narrative fails instead of coercing silently', () => {
  assert.throws(() => contract.inlineTokens({ text: 'invalid' }), /string/);
});
test('stable hashes distinguish different generated bytes', () => {
  assert.equal(contract.digest(Buffer.from('synthetic')), contract.digest(Buffer.from('synthetic')));
  assert.notEqual(contract.digest(Buffer.from('synthetic')), contract.digest(Buffer.from('different')));
});
test('inert JSON rejects duplicate keys and preserves literal values', () => {
  assert.throws(() => contract.parseJson('{"schema":1,"schema":1}'), /Duplicate/);
  assert.deepEqual(contract.parseJson('{"value":"$$ {{BODY}}","items":[null,1,true]}'),
    { value: '$$ {{BODY}}', items: [null, 1, true] });
});
test('network namespaces are rejected before any Node filesystem probe', () => {
  const fs = require('node:fs');
  const previous = fs.lstatSync;
  let called = false;
  fs.lstatSync = () => { called = true; throw Error('filesystem must not be probed'); };
  try {
    for (const value of ['//synthetic.invalid/share/file', '\\\\?\\UNC\\synthetic.invalid\\share\\file', 'smb://synthetic.invalid/share']) {
      assert.throws(() => contract.noLinks(value), /Network/);
    }
    assert.equal(called, false);
  } finally {
    fs.lstatSync = previous;
  }
});
