"""One offline quality gate; installs nothing and uses synthetic data only."""
from __future__ import annotations

import ast
from importlib.metadata import version
import json
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys
import unittest

from review_content import candidate_files, history_findings, review
from project import json_object

PYTHON_SUITES = ("test_project.py", "test_capture.py", "test_reports.py",
                 "test_onboarding.py", "test_content_review.py", "test_quality_gate.py")
NODE_SUITE = "report_contract.test.cjs"
NODE_CASES = ("adjacent and sparse citation tokens remain distinct",
              "nested emphasis preserves the cited text and ID",
              "plain caption text contains citation numbers without markup",
              "non-string narrative fails instead of coercing silently",
              "stable hashes distinguish different generated bytes")


def verify_node_dependencies(scripts: Path) -> None:
    manifest = json_object((scripts / "package.json").read_text(encoding="utf-8"))
    lock = json_object((scripts / "package-lock.json").read_text(encoding="utf-8"))
    packages = lock.get("packages")
    if lock.get("lockfileVersion") != 3 or not isinstance(packages, dict) or not isinstance(packages.get(""), dict):
        raise ValueError("report dependency lock must be a complete version-3 lock")
    root = packages[""]
    for key in ("name", "version"):
        if not manifest.get(key) or lock.get(key) != manifest[key] or root.get(key) != manifest[key]:
            raise ValueError("report manifest/lock identity differs")
    for key in ("dependencies", "devDependencies", "optionalDependencies"):
        declared, locked = manifest.get(key, {}), root.get(key, {})
        if not isinstance(declared, dict) or not isinstance(locked, dict) or declared != locked:
            raise ValueError("report manifest/lock dependency declarations differ")
        for name, expected in declared.items():
            if not re.fullmatch(r"(?:@[a-z0-9._-]+/)?[a-z0-9._-]+", name) or not isinstance(expected, str) or not re.fullmatch(r"\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?", expected):
                raise ValueError("direct report dependencies require exact version pins")
            entry = packages.get(f"node_modules/{name}")
            if not isinstance(entry, dict) or entry.get("version") != expected:
                raise ValueError(f"locked direct dependency differs from manifest: {name}")
    base = scripts.resolve()
    for relative, entry in packages.items():
        if not relative:
            continue
        parts = PurePosixPath(relative).parts
        if not parts or parts[0] != "node_modules" or ".." in parts or not isinstance(entry, dict):
            raise ValueError("unsupported dependency lock path/entry")
        installed = (scripts / relative / "package.json").resolve()
        if not installed.is_relative_to(base):
            raise ValueError("installed dependency escapes the declared local dependency directory")
        package = json_object(installed.read_text(encoding="utf-8"))
        if not isinstance(entry.get("version"), str) or package.get("version") != entry["version"]:
            raise ValueError(f"installed dependency version differs from lock: {relative}")


def collect_python(root: Path, required: tuple[str, ...] = PYTHON_SUITES) -> unittest.TestSuite:
    tests = root / "tests"
    for name in required:
        if not (tests / name).is_file():
            raise ValueError(f"required test suite is missing: {name}")
    previous_path = sys.path[:]
    try:
        loader = unittest.TestLoader()
        suite = loader.discover(str(tests), pattern="test_*.py", top_level_dir=str(tests))
        if loader.errors:
            raise ValueError("test discovery failed: " + "; ".join(loader.errors))
    finally:
        sys.path[:] = previous_path
    counts = {Path(name).stem: 0 for name in required}
    def count(value):
        if isinstance(value, unittest.TestSuite):
            for item in value:
                count(item)
        else:
            name = type(value).__module__
            if name in counts:
                counts[name] += 1
    count(suite)
    if any(value == 0 for value in counts.values()):
        raise ValueError("required suites collected no tests: " + ", ".join(name for name, value in counts.items() if not value))
    return suite


def require_python_success(result: unittest.TestResult, expected: int) -> None:
    if expected < 1 or result.testsRun != expected or not result.wasSuccessful() or result.skipped or result.expectedFailures:
        raise ValueError("Python gate requires all declared tests to run successfully, without skips or expected failures")


def require_node_success(output: str) -> int:
    counts = {}
    for name in ("tests", "pass", "fail", "cancelled", "skipped", "todo"):
        matches = re.findall(rf"(?m)^# {name} (\d+)\r?$", output)
        if len(matches) != 1:
            raise ValueError(f"Node TAP summary missing/ambiguous: {name}")
        counts[name] = int(matches[0])
    if counts["tests"] < 1 or counts["pass"] != counts["tests"] or any(
            counts[name] for name in ("fail", "cancelled", "skipped", "todo")):
        raise ValueError("Node gate requires nonzero passing tests without skips, cancellations or todo cases")
    names = set(re.findall(r"(?m)^# Subtest: ([^\r\n]+)", output))
    if not set(NODE_CASES).issubset(names):
        raise ValueError("required named Node cases were not executed")
    return counts["tests"]


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    try:
        if sys.version_info < (3, 12):
            raise ValueError("Python 3.12 or newer is required")
        for line in (root / "requirements.txt").read_text(encoding="utf-8").splitlines():
            name, expected = line.split("==")
            if version(name) != expected:
                raise ValueError(f"install the declared {name}=={expected} in this environment")
        scripts = root / "tools" / "report" / "scripts"
        verify_node_dependencies(scripts)
        check = subprocess.run(["node", "-e",
            "if(Number(process.versions.node.split('.')[0]) < 24) throw Error('Node 24 required'); require('docx'); require('image-size');"],
            cwd=scripts, check=True, capture_output=True, text=True)
        if check.stdout:
            print(check.stdout)
        files, errors = candidate_files(root)
        errors.extend(review(root))
        errors.extend(history_findings(root))
        if errors:
            raise ValueError("; ".join(sorted(set(errors))))
        for path in files:
            if path.suffix == ".py":
                ast.parse(path.read_text(encoding="utf-8"), filename=str(path.relative_to(root)))
            elif path.suffix in (".js", ".cjs"):
                subprocess.run(["node", "--check", str(path)], check=True, capture_output=True, text=True)
            elif path.suffix == ".json":
                json.loads(path.read_text(encoding="utf-8"))
        suite = collect_python(root)
        expected = suite.countTestCases()
        result = unittest.TextTestRunner(verbosity=2).run(suite)
        require_python_success(result, expected)
        node_suite = root / "tests" / NODE_SUITE
        if not node_suite.is_file():
            raise ValueError("required Node test suite is missing")
        node = subprocess.run(["node", "--test", "--test-reporter=tap", str(node_suite)],
                              cwd=root, check=True, capture_output=True, text=True)
        print(node.stdout)
        require_node_success(node.stdout)
        print("PASS: offline synthetic gate. Manual privacy, history and publication review is still required.")
        return 0
    except (OSError, ValueError, ImportError, SyntaxError, subprocess.SubprocessError) as exc:
        print(f"ERROR: quality gate incomplete or failed: {exc}", file=sys.stderr)
        if isinstance(exc, subprocess.CalledProcessError) and exc.stderr:
            print(exc.stderr, file=sys.stderr)
        if isinstance(exc, subprocess.CalledProcessError) and exc.stdout:
            print(exc.stdout, file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
